/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R1RouteImport } from './routes/1'
import { Route as R2RouteImport } from './routes/2'
import { Route as R3RouteImport } from './routes/3'
import { Route as R4RouteImport } from './routes/4'
import { Route as R5RouteImport } from './routes/5'
import { Route as R6RouteImport } from './routes/6'
import { Route as R7RouteImport } from './routes/7'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R1Route = R1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => rootRouteImport,
} as any)
const R2Route = R2RouteImport.update({
  id: '/2',
  path: '/2',
  getParentRoute: () => rootRouteImport,
} as any)
const R3Route = R3RouteImport.update({
  id: '/3',
  path: '/3',
  getParentRoute: () => rootRouteImport,
} as any)
const R4Route = R4RouteImport.update({
  id: '/4',
  path: '/4',
  getParentRoute: () => rootRouteImport,
} as any)
const R5Route = R5RouteImport.update({
  id: '/5',
  path: '/5',
  getParentRoute: () => rootRouteImport,
} as any)
const R6Route = R6RouteImport.update({
  id: '/6',
  path: '/6',
  getParentRoute: () => rootRouteImport,
} as any)
const R7Route = R7RouteImport.update({
  id: '/7',
  path: '/7',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1': typeof R1Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/6': typeof R6Route
  '/7': typeof R7Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1': typeof R1Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/6': typeof R6Route
  '/7': typeof R7Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1': typeof R1Route
  '/2': typeof R2Route
  '/3': typeof R3Route
  '/4': typeof R4Route
  '/5': typeof R5Route
  '/6': typeof R6Route
  '/7': typeof R7Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/1' | '/2' | '/3' | '/4' | '/5' | '/6' | '/7'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/1' | '/2' | '/3' | '/4' | '/5' | '/6' | '/7'
  id: '__root__' | '/' | '/1' | '/2' | '/3' | '/4' | '/5' | '/6' | '/7'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1Route: typeof R1Route
  R2Route: typeof R2Route
  R3Route: typeof R3Route
  R4Route: typeof R4Route
  R5Route: typeof R5Route
  R6Route: typeof R6Route
  R7Route: typeof R7Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1': {
      id: '/1'
      path: '/1'
      fullPath: '/1'
      preLoaderRoute: typeof R1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2': {
      id: '/2'
      path: '/2'
      fullPath: '/2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3': {
      id: '/3'
      path: '/3'
      fullPath: '/3'
      preLoaderRoute: typeof R3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4': {
      id: '/4'
      path: '/4'
      fullPath: '/4'
      preLoaderRoute: typeof R4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5': {
      id: '/5'
      path: '/5'
      fullPath: '/5'
      preLoaderRoute: typeof R5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/6': {
      id: '/6'
      path: '/6'
      fullPath: '/6'
      preLoaderRoute: typeof R6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/7': {
      id: '/7'
      path: '/7'
      fullPath: '/7'
      preLoaderRoute: typeof R7RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1Route: R1Route,
  R2Route: R2Route,
  R3Route: R3Route,
  R4Route: R4Route,
  R5Route: R5Route,
  R6Route: R6Route,
  R7Route: R7Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
